baseURL = 'https://yotom131.github.io'
languageCode = 'en-us'
title = 'Yo blog'
theme = 'stack'
paginate = 8
DefaultContentLanguage = 'zh-cn'
hasCJKLanguage = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1